
name: '[Demo_1] Build & Test'
run-name: Simple Build & Test 

on:
  workflow_dispatch: 
  push:
    branches:
      - main

env:
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON

      - name: Build Project
        run: cmake --build build/ --config ${{env.BUILD_TYPE}}

      - name: Run Tests
        run: ctest --test-dir build/


