name: Build & Test

on:
  push:
    branches:
      - master
env:
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Configure CMake
        run: cmake -B build/ -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build build/ --config ${{ env.BUILD_TYPE }}

      - name: Run Tests
        run: ctest --test-dir build/ --output-on-failure

